sudo: false
language: rust
rust:
- 1.22.0  # Two releases back
- stable
- beta
- nightly

cache:
  cargo: true

matrix:
  include:
  - rust: 1.24.0  # `stable`: Locking down for consistent behavior
    env: RUSTFLAGS="-D warnings"
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo check --tests
    - cargo fmt -- --write-mode=diff
  - rust: nightly-2018-01-14
    env: CLIPPY_VERSION=0.0.179
    install:
    - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
    - cargo clippy -- -D clippy

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose

branches:
  only:
    - staging # bors r+
    - trying # bors try
    - master
