sudo: false
language: rust
rust:
- stable
- 1.22.0  # Min Rust Version
- beta
- nightly

cache:
  cargo: true

matrix:
  include:
  # Warnings + Rustfmt
  - rust: 1.30.1
    name: style
    install:
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    script:
    - cargo clippy --all-targets --tests -- -D warnings
    - cargo fmt -- --write-mode=diff
  # GitHub Pages
  - env: CARGO_GHP_VERSION=0.3.2
    script:
    - cargo rustdoc --verbose -- --document-private-items
    install:
    - cargo install cargo-ghp-upload --version $CARGO_GHP_VERSION || echo "cargo-ghp-upload already installed"
    after_success:
    - cargo ghp-upload -vvvr
  allow_failures:
  - env: CARGO_GHP_VERSION=0.3.2
  fast_finish: true

script:
- cargo build --verbose
- cargo test --verbose

branches:
  only:
  - staging # bors r+
  - trying # bors try
  - /^\d+\.\d+\.\d+(-\S*)?$/ # releases
  - master
